### ISSUE TITLE
紅點要有延續性

### ISSUE THREAD

**Issue by DeyuGoGo** [DeyuGoGo/BloodScreen#1]
下次要出現上次出現的點。

**Comment by DeyuGoGo** [comment]
finish

**Comment by chentsulin** [comment]
如果在 commit 裡面附加 關鍵字可以自動 close issue
https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by DeyuGoGo** [comment]
我早上試了一下，不行啊，是要merge 到 master才會close?

**Comment by chentsulin** [comment]
merged into the default branch

你現在 default 應該是 master
